#!/bin/bash

commit_msg=${1:-"update"}
bin=${2:-$(pwd)}
bin=${bin##*/}

if [ -z "$bin" ] ; then
    exit 1
fi

go build -o $bin *.go

for file in README.md TODO.md secretary ; do

    cp $file ./release/ 

    echo -e "\033[33m\tcopy [ $file ] to [ ./release/$file ]\033[m"

done

cd release

echo -e "\033[33m\tcommit -m $commit_msg\033[m"
git add --all
git commit -m "$commit_msg"
git push release master --tags

cd -

