#!/bin/bash

commit_msg=${1:-"update"}
bin=${2:-$(pwd)}
bin=${bin##*/}
release=./release

if [ -z "$bin" ] ; then
    exit 1
fi

# go build -o $bin *.go

if [ ! -d "$release" ] ; then
    mkdir $release
fi

for file in README.md TODO.md $bin ; do

    cp $file $release 

    echo -e "\033[33m\tcopy [ $file ] to [ ./release/$file ]\033[m"

done

if [ -d $release/.git ] ; then

    cd $release
    
    echo -e "\033[33m\tcommit -m $commit_msg\033[m"
    git add --all
    git commit -m "$commit_msg"
    git push release master --tags
    
    cd -
fi

